export const A7_DECK_SECTIONS = [
  { id: 'slide-1', label: '01. Титул' },
  { id: 'slide-2', label: '02. А7 сегодня' },
  { id: 'slide-3', label: '03. Стратегическая проблема' },
  { id: 'slide-4', label: '04. Семья — место спроса' },
  { id: 'slide-5', label: '05. Позиционирование' },
  { id: 'slide-6', label: '06. Было / стало' },
  { id: 'slide-7', label: '07. Карта направлений' },
  { id: 'slide-8', label: '08. Семейные финцели' },
  { id: 'slide-9', label: '09. Международные платежи' },
  { id: 'slide-10', label: '10. Канал для «А7 Финансы»' },
  { id: 'slide-11', label: '11. Инфраструктурный партнёр' },
  { id: 'slide-12', label: '12. Архитектура ролей' },
  { id: 'slide-13', label: '13. Зрелость платформы' },
  { id: 'slide-14', label: '14. Пилот «А7 Семейные цели»' },
  { id: 'slide-15', label: '15. KPI пилота' },
  { id: 'slide-16', label: '16. Финансовая модель' },
  { id: 'slide-17', label: '17. Инвестиционная модель' },
  { id: 'slide-18', label: '18. Ask и план' },
];
