ALTER TABLE t_p5815085_family_assistant_pro.children_activities
  ADD COLUMN IF NOT EXISTS days_of_week INTEGER[],
  ADD COLUMN IF NOT EXISTS time_of_day VARCHAR(10),
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS started DATE,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS calendar_event_id INTEGER;
